FROM python:3.10-slim

# Install required tools
RUN pip install mlflow

# Create mlflow directories with proper permissions
RUN mkdir -p /mlflow/artifacts && \
    addgroup --system mlflow && \
    adduser --system --ingroup mlflow mlflow && \
    chown -R mlflow:mlflow /mlflow && \
    chmod -R 775 /mlflow

# Switch to non-root user
USER mlflow

# Expose port
EXPOSE 5000

# Entrypoint will be passed from docker-compose
